### PR TITLE
Correct C++ related makefile variables

### PR DESCRIPTION
**Pull request by arkamar**
FINAL_CXXFLAGS should not inherit CFLAGS because they can contain C
specific options unsupported by C++.

REDIS_CXX should point to the C++ compiler rather than C.

### CODE REVIEW

**Comment by JohnSully** [comment]
Hi @arkamar

The reason for the original behavior is because there are a bunch of scripts that only set CFLAGS. However this is the right approach. 

Let me do a review of CFLAGS before merging.

**Comment by JohnSully** [comment]
@arkamar There are quite a few places where only CFLAGS is set and not CXXFLAGS.  I'll merge this and fix in unstable.

**Comment by JohnSully** [comment]
Change cda8d42a has additional fixes.

**Comment by arkamar** [comment]
Thanks!

**Pull request merged**
