### PR TITLE
fixes for robj_sharedptr

### PR DESCRIPTION
**Pull request by tryfinally**
1. fix cases where null pointer might be accessed
2. make assignmnet op safe
3. make operator bool explicit (safe bool idiom)
4. make comparison operators symetric

fix robj_sharedptr use in rdb.cpp

### CODE REVIEW

**Comment by JohnSully** [comment]
Quick style note, we don’t in general import std:: namespace objects into global namespace. Just use std::swap.

**Comment by tryfinally** [comment]
@JohnSully Please note that I did not import the whole name space into the global.
it's inside a function. ( no pollution of global namespace )
```
using std::swap;
swap(m_ptr, tmp.m_ptr);
```

**Comment by JohnSully** [comment]
Yea I saw that. I’d still prefer to just use std::swap like we do elsewhere if style is the only differentiator. 

Aside from style is there a technical reason to use your syntax?

**Comment by tryfinally** [comment]
@JohnSully this is the "right" c++ idiom for using swap. its not a style thing.
you should always
```
use  std::swap;
swap(a,b);
```
this way the compiler will choose among the swap functions set available in your global + std the most appropriate one. 
See **Effective C++ Third Edition 55 Specific Ways to Improve Your Programs and Designs**
By _Scott Meyers_
Item 25 @ Page 129

**Comment by JohnSully** [comment]
I think that’s compelling but in that case should we not globally enable it with a using clause at the top of server.h?

FWIW I’d still consider this an exception. I’m a bit worried about global namespace pollution and consistency.

**Comment by tryfinally** [comment]
@JohnSully there is no global namespace pollution here. You should always use std::swap 
as I showed. I would recommend Scott's book.
If it's not available see [C++ Core Guideline](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c165-use-using-for-customization-points)
a long discussion by C++ big guns on [omp.lang.c++.moderated](https://groups.google.com/forum/#!topic/comp.lang.c++.moderated/s5b-2tfc3IE%5B1-25%5D)


_just documented reason for this for future reference._

**Comment by JohnSully** [comment]
What I’m saying is, should we not put the using clause globally rather than duplicating it in every function we use std::swap?

If the best practice is to use an undecorated swap why not make that easy everywhere?

**Comment by tryfinally** [comment]
@JohnSully Using-declaration introduces a member of another namespace into current  block scope.
if it's done global it will pollute the name global namespace and will have consequences.
Again, I provided links to explain and hear C++ experts. No need to replicate this here.

**Comment by JohnSully** [comment]
I know what using does. You’ve convinced me the benefits of undecorated swap outweigh the cost of namespace pollution. 

Taking this to its logical conclusion enforcing use of explicit std::swap should be discouraged. Thus it makes no sense for this to be the easiest way to access swap() and duplicate a using clause everywhere swap is used. 

In general I think implicit overrides of the stdlib is a bad thing but I don’t think most of the horror cases apply to std::swap hence the exception of allowing this pollution.

**Comment by JohnSully** [comment]
In other words you’ve won the argument. The question now is what does that mean for codebase as a whole.

**Comment by JohnSully** [comment]
Merging as is.  Still think we should put the using globally.

**Pull request merged**
