### PR TITLE
fixes for robj_sharedptr

### PR DESCRIPTION
**Pull request by tryfinally**
1. fix cases where null pointer might be accessed
2. make assignmnet op safe
3. make operator bool explicit (safe bool idiom)
4. make comparison operators symetric

### CODE REVIEW

**Comment by JohnSully** [comment]
Super happy about this!  Been meaning to clean that up for a while. 

I’ll take a bit of time to review then merge.

**Comment by tryfinally** [comment]
@JohnSully  I missed one thing, will fix and resubmit!

**Comment by JohnSully** [comment]
You can always update the source branch and it will be reflected in the PR automatically.

**Comment by tryfinally** [comment]
Any response?

**Comment by JohnSully** [comment]
Hey @tryfinally I was waiting to continue the discussion on the replacement PR.  Anyways debates over where using should go and worth delaying an otherwise good fix so I merged it to unstable.

Thanks for you contributions I really appreciate it!

**Pull request closed without merging**
